apiVersion: v1
kind: Service
metadata:
  name: digital-human
  labels:
    app: digital-human
spec:
  sessionAffinity: ClientIP
  type: ClusterIP
  ports:
  - port: 8080
    protocol: TCP
  selector:
    app: digital-human